create database employer;
use employer;
CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY,
FNAME VARCHAR(50) NOT NULL,
LNAME VARCHAR(50),
CONTACT VARCHAR(13) NOT NULL,
MAIL VARCHAR(100),
AGE INT NOT NULL,
SEX VARCHAR (10),
DEGREE VARCHAR(100) NOT NULL,
ROLE VARCHAR(50) NOT NULL,
SALARY VARCHAR(10) NOT NULL,
IMG LONGBLOB NOT NULL);
SHOW databases;
SHOW TABLES;
SELECT * FROM EMPLOYEES;